const ASSETS=[
['MSCI World','IE000ZYRH0Q7','SWDA.L',25],['S&P 500','IE0032126645','CSPX.L',5],['World Value','IE00BP3QZB59','IWVL.L',15],['EM Value','IE00BG0SKF03','EMVL.L',10],['World IT','IE00BM67HT60','XDWT.L',5],['AI Infrastructure','IE000X59ZHE2','AINF.L',5],['Defense','IE000YYE6WK5','DFNS.L',4],['Uranium / Nuclear','IE0003BJ2JS4','NCLR.L',4],['Strategic Metals','IE000KHX9DX6','WENU.L',3],['Physical Gold','', 'SGLN.L',8]
];
const $=s=>document.querySelector(s); const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
let state=JSON.parse(localStorage.getItem('mr_state')||'null')||{view:'dashboard',eodKey:'',fredKey:'',monthly:1000,reserve:6755,data:{},macro:null,lastUpdate:null};
function save(){localStorage.setItem('mr_state',JSON.stringify(state))} function avg(a){return a.reduce((x,y)=>x+y,0)/a.length}
function sma(a,n){return a.length>=n?avg(a.slice(-n)):null} function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];d>0?g+=d:l-=d}return l===0?100:100-(100/(1+(g/n)/(l/n)))}
function calc(prices){if(prices.length<220)return null;let p=prices.at(-1),m50=sma(prices,50),m200=sma(prices,200),hi=Math.max(...prices.slice(-252)),mom=prices.length>252?p/prices.at(-253)-1:p/prices[0]-1,dd=p/hi-1,r=rsi(prices);let trend=0;trend+=p>m200?30:5;trend+=m50>m200?25:5;trend+=clamp(25+mom*100,0,25);trend+=clamp(20+(r-50)*.4,0,20);let draw=clamp((-dd)*180+35,20,90);return{p,m50,m200,mom,dd,r,trend:clamp(trend),draw}}
function action(s){return s>=80?'COMPRAR FUERTE':s>=65?'COMPRAR':s>=45?'DCA NORMAL':s>=25?'ESPERAR':'NO AÑADIR'}
function opportunity(t,macro=50){return Math.round(.55*t.trend+.25*t.draw+.20*macro)}
async function eod(symbol){let u=`https://eodhd.com/api/eod/${encodeURIComponent(symbol)}?api_token=${encodeURIComponent(state.eodKey)}&fmt=json&period=d&from=${new Date(Date.now()-1000*86400*500).toISOString().slice(0,10)}`;let r=await fetch(u);if(!r.ok)throw Error('EODHD '+r.status);let j=await r.json();return j.filter(x=>x.adjusted_close||x.close).map(x=>+(x.adjusted_close||x.close))}
async function fred(series){let u=`https://api.stlouisfed.org/fred/series/observations?series_id=${series}&api_key=${encodeURIComponent(state.fredKey)}&file_type=json&sort_order=desc&limit=2`;let r=await fetch(u);if(!r.ok)throw Error('FRED '+r.status);let j=await r.json();return +j.observations.find(x=>x.value!=='.').value}
async function refresh(){if(!state.eodKey)return alert('Añade tu API key de EODHD en Ajustes.'); let btn=$('#refresh');if(btn){btn.disabled=true;btn.textContent='Actualizando…'};try{let macro=50;if(state.fredKey){try{let [vix,hy,curve]=await Promise.all([fred('VIXCLS'),fred('BAMLH0A0HYM2'),fred('T10Y2Y')]);macro=clamp(68-vix*.7-hy*2+curve*4);state.macro={vix,hy,curve,score:Math.round(macro)}}catch(e){console.warn(e)}} for(let a of ASSETS){try{let prices=await eod(a[2]);let t=calc(prices);if(t)state.data[a[1]||a[2]]={...t,score:opportunity(t,macro),updated:Date.now()}}catch(e){console.warn(a[0],e)}}state.lastUpdate=Date.now();save();render()}catch(e){alert('No se pudo actualizar: '+e.message)}finally{if(btn){btn.disabled=false;btn.textContent='Actualizar'}}}
function sampleIfEmpty(){if(Object.keys(state.data).length)return;ASSETS.forEach((a,i)=>state.data[a[1]||a[2]]={p:100+i*3,m50:98,m200:94,mom:.08-i*.006,dd:-.04-i*.006,r:55,trend:62-i,draw:42+i,score:Math.round(58+i*.7),demo:true})}
function dashboard(){sampleIfEmpty();let rows=ASSETS.map(a=>[a,state.data[a[1]||a[2]]]).filter(x=>x[1]);let global=Math.round(avg(rows.slice(0,4).map(x=>x[1].score)));let macro=state.macro?.score??50;return `<div class="top"><div><div class="brand">Market Radar</div><div class="muted">${state.lastUpdate?'Actualizado '+new Date(state.lastUpdate).toLocaleString():'Modo demostración'}</div></div><button id="refresh" class="btn primary">Actualizar</button></div><div class="hero"><div class="heroRow"><div><div class="muted" style="color:#d0d5dd">GLOBAL MARKET SCORE</div><div class="score">${global}</div><span class="pill">${action(global)}</span></div><div class="right"><div class="muted" style="color:#d0d5dd">DCA mensual</div><b>${state.monthly.toLocaleString('es-ES')} €</b></div></div><div class="grid"><div class="stat"><div class="muted" style="color:#d0d5dd">Macro</div><b>${macro}/100</b></div><div class="stat"><div class="muted" style="color:#d0d5dd">Reserva</div><b>${state.reserve.toLocaleString('es-ES')} €</b></div><div class="stat"><div class="muted" style="color:#d0d5dd">Activos</div><b>${ASSETS.length}</b></div><div class="stat"><div class="muted" style="color:#d0d5dd">Régimen</div><b>${macro>60?'Risk-on':macro<35?'Risk-off':'Neutral'}</b></div></div></div><div class="section"><h2>Radar</h2><div class="assetList">${rows.map(([a,d])=>assetCard(a,d)).join('')}</div></div>`}
function assetCard(a,d){return `<div class="card"><div class="assetHead"><div><div class="assetName">${a[0]}</div><div class="small">Objetivo ${a[3]}% · ${a[1]||a[2]}</div></div><div class="right"><div class="assetScore">${d.score}</div><div class="small">${action(d.score)}</div></div></div><div class="bar"><div class="fill" style="width:${d.score}%"></div></div><div class="metrics"><div class="metric">Tendencia<b>${Math.round(d.trend)}</b></div><div class="metric">Drawdown<b>${(d.dd*100).toFixed(1)}%</b></div><div class="metric">Momentum<b>${(d.mom*100).toFixed(1)}%</b></div><div class="metric">RSI<b>${d.r?.toFixed(0)||'—'}</b></div></div></div>`}
function ranking(){sampleIfEmpty();let r=ASSETS.map(a=>({a,d:state.data[a[1]||a[2]]})).filter(x=>x.d).sort((x,y)=>y.d.score-x.d.score);let weights=r.map(x=>Math.max(0,x.d.score-45)),sum=weights.reduce((a,b)=>a+b,0)||1;return `<div class="top"><div><div class="brand">Compra del mes</div><div class="muted">Ranking por Opportunity Score</div></div></div><div class="notice">V1 usa tendencia, drawdown y macro. La valoración/breadth se incorporará cuando haya una fuente histórica fiable para cada índice. No interpreta el score como predicción garantizada.</div><div class="section">${r.map((x,i)=>{let amt=Math.round(state.monthly*weights[i]/sum/10)*10;return `<div class="card rank"><div class="rankNo">${i+1}</div><div class="grow"><div class="assetName">${x.a[0]}</div><div class="small">Score ${x.d.score} · ${action(x.d.score)}</div></div><div class="amount">${amt} €</div></div>`}).join('')}</div>`}
function settings(){return `<div class="top"><div><div class="brand">Ajustes</div><div class="muted">Las claves se guardan sólo en este dispositivo</div></div></div><div class="card"><label class="field"><span>EODHD API key</span><input id="eod" type="password" value="${state.eodKey}" placeholder="Tu API key"></label><label class="field"><span>FRED API key (opcional)</span><input id="fred" type="password" value="${state.fredKey}" placeholder="Tu API key"></label><label class="field"><span>Aportación mensual (€)</span><input id="monthly" type="number" value="${state.monthly}"></label><label class="field"><span>Reserva disponible (€)</span><input id="reserve" type="number" value="${state.reserve}"></label><button id="saveSettings" class="btn primary">Guardar</button></div><div class="section"><div class="notice good"><b>Privacidad:</b> cartera, configuración y claves permanecen en localStorage del navegador. No existe servidor propio ni cuenta de usuario.</div></div><div class="section"><button id="clear" class="btn">Borrar datos locales</button></div>`}
function render(){let body=state.view==='dashboard'?dashboard():state.view==='ranking'?ranking():settings();document.querySelector('#app').innerHTML=`<main class="shell">${body}</main><nav class="tabs"><div><div class="tab ${state.view==='dashboard'?'active':''}" data-v="dashboard">Radar</div><div class="tab ${state.view==='ranking'?'active':''}" data-v="ranking">Comprar</div><div class="tab ${state.view==='settings'?'active':''}" data-v="settings">Ajustes</div></div></nav>`;document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>{state.view=x.dataset.v;save();render()});$('#refresh')&&($('#refresh').onclick=refresh);$('#saveSettings')&&($('#saveSettings').onclick=()=>{state.eodKey=$('#eod').value.trim();state.fredKey=$('#fred').value.trim();state.monthly=+$('#monthly').value||1000;state.reserve=+$('#reserve').value||0;save();state.view='dashboard';render()});$('#clear')&&($('#clear').onclick=()=>{if(confirm('¿Borrar configuración y datos locales?')){localStorage.removeItem('mr_state');location.reload()}})}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
