'use strict';
function avg(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function clamp(x,a=0,b=100){return Math.max(a,Math.min(b,x))}
function maxDrawdown(values){let peak=-Infinity,dd=0;for(const v of values){peak=Math.max(peak,v);if(peak>0)dd=Math.min(dd,v/peak-1)}return dd}
function xirr(flows){if(flows.length<2)return NaN;const t0=new Date(flows[0].date),npv=r=>flows.reduce((s,x)=>s+x.value/Math.pow(1+r,(new Date(x.date)-t0)/31557600000),0);let lo=-.9999,hi=10,nlo=npv(lo),nhi=npv(hi);if(!Number.isFinite(nlo)||!Number.isFinite(nhi)||nlo*nhi>0)return NaN;for(let i=0;i<150;i++){const mid=(lo+hi)/2,nm=npv(mid);if(nlo*nm<=0){hi=mid;nhi=nm}else{lo=mid;nlo=nm}}return(lo+hi)/2}
function metrics(series,flows){if(series.length<2)return null;const returns=[];for(let i=1;i<series.length;i++){const base=series[i-1].value+(series[i].flow||0);if(base>0)returns.push(series[i].value/base-1)}const growth=returns.reduce((p,r)=>p*(1+r),1),ann=Math.pow(growth,252/Math.max(1,returns.length))-1,m=avg(returns),sd=Math.sqrt(avg(returns.map(r=>(r-m)**2))),end=series.at(-1);return{final:end.value,twrAnnual:ann,volAnnual:sd*Math.sqrt(252),sharpe:sd?m/sd*Math.sqrt(252):0,maxDD:maxDrawdown(series.map(x=>x.value)),xirr:xirr([...flows,{date:end.date,value:end.value}])}}
function sma(p,n,i){if(i+1<n)return null;let s=0;for(let j=i-n+1;j<=i;j++)s+=p[j];return s/n}
function rsi(p,n,i){if(i<n)return null;let g=0,l=0;for(let j=i-n+1;j<=i;j++){const d=p[j]-p[j-1];if(d>0)g+=d;else l-=d}return l?100-100/(1+(g/n)/(l/n)):100}
function opportunity(prices,i,macro=50){if(i<252)return 50;const p=prices[i],m50=sma(prices,50,i),m200=sma(prices,200,i),hi=Math.max(...prices.slice(i-251,i+1)),mom=p/prices[i-252]-1,rr=rsi(prices,14,i),dd=p/hi-1,trend=clamp((p>m200?30:5)+(m50>m200?25:5)+clamp(25+mom*100,0,25)+clamp(20+(rr-50)*.4,0,20)),draw=clamp((-dd)*180+35,20,90);return clamp(.55*trend+.25*draw+.20*macro)}
function drawdownAt(prices,i){if(i<20)return 0;const start=Math.max(0,i-251),hi=Math.max(...prices.slice(start,i+1));return prices[i]/hi-1}
function smartWeights({assets,weights,values,total,priceArrays,i}){const wsum=weights.reduce((a,b)=>a+b,0),rows=assets.map((a,k)=>{const target=weights[k]/wsum,actual=total?values[k]/total:0,deficit=clamp((target-actual)/Math.max(target,.0001),-1,1),dd=drawdownAt(priceArrays[k],i),draw=clamp((-dd)/.20,0,1),deficit01=clamp((deficit+1)/2,0,1),score=.80*draw+.20*deficit01;return{target,score}});const base=.50,tilt=.50,pos=rows.map(r=>Math.max(.05,r.score)),ps=pos.reduce((a,b)=>a+b,0)||1;let out=rows.map((r,k)=>base*r.target+tilt*pos[k]/ps),cap=.40;for(let pass=0;pass<8;pass++){let excess=0,free=[];for(let k=0;k<out.length;k++){if(out[k]>cap){excess+=out[k]-cap;out[k]=cap}else free.push(k)}if(excess<1e-12||!free.length)break;const den=free.reduce((s,k)=>s+out[k],0)||free.length;for(const k of free)out[k]+=excess*(den===free.length?1/free.length:out[k]/den)}const sum=out.reduce((a,b)=>a+b,0)||1;return out.map(x=>x/sum)}
function alignAssets(assets){if(assets.length<2)throw new Error('Need >=2 assets');const maps=assets.map(a=>new Map(a.history.map(x=>[x.date,+x.close])));const dates=[...maps[0].keys()].filter(d=>maps.every(m=>m.has(d))).sort();if(dates.length<253)throw new Error('Need >=253 common sessions');return{dates,maps}}
function simulate({assets,monthly=1000,macroAt=()=>50,startIndex=252}){const{dates,maps}=alignAssets(assets),weights=assets.map(a=>a.weight),wsum=weights.reduce((a,b)=>a+b,0),names=['DCA','REBALANCE','MR_TECH','MR_MACRO','SMART_DCA'],shares=Object.fromEntries(names.map(n=>[n,assets.map(()=>0)])),cash=Object.fromEntries(names.map(n=>[n,0])),series=Object.fromEntries(names.map(n=>[n,[]])),flows=Object.fromEntries(names.map(n=>[n,[]])),priceArrays=maps.map(m=>dates.map(d=>m.get(d)));let contributed=0,lastMonth='',contributionCount=0,minCash=Object.fromEntries(names.map(n=>[n,Infinity])),maxSmartWeight=0;
for(let i=startIndex;i<dates.length;i++){const date=dates[i],prices=priceArrays.map(p=>p[i]),month=date.slice(0,7),isContribution=month!==lastMonth,flow=isContribution?monthly:0;if(isContribution){lastMonth=month;contributionCount++;contributed+=monthly;for(const n of names){cash[n]+=monthly;flows[n].push({date,value:-monthly})}
assets.forEach((a,k)=>{const amt=monthly*weights[k]/wsum;shares.DCA[k]+=amt/prices[k];cash.DCA-=amt});
const rv=assets.map((a,k)=>shares.REBALANCE[k]*prices[k]),rt=rv.reduce((a,b)=>a+b,0)+cash.REBALANCE,gaps=assets.map((a,k)=>Math.max(0,rt*weights[k]/wsum-rv[k])),gs=gaps.reduce((a,b)=>a+b,0);assets.forEach((a,k)=>{const amt=gs?monthly*gaps[k]/gs:monthly*weights[k]/wsum;shares.REBALANCE[k]+=amt/prices[k];cash.REBALANCE-=amt});
for(const n of ['MR_TECH','MR_MACRO']){const vals=assets.map((a,k)=>shares[n][k]*prices[k]),total=vals.reduce((a,b)=>a+b,0)+cash[n],macro=n==='MR_MACRO'?macroAt(date):50,scores=assets.map((a,k)=>{const opp=opportunity(priceArrays[k],i,macro),actual=total?vals[k]/total*100:0,target=weights[k]/wsum*100,under=target-actual;return clamp(.65*opp+.35*clamp(50+under*4))}),bw=scores.map(s=>Math.max(0,s-40)),bs=bw.reduce((a,b)=>a+b,0);assets.forEach((a,k)=>{const amt=bs?monthly*bw[k]/bs:monthly*weights[k]/wsum;shares[n][k]+=amt/prices[k];cash[n]-=amt})}
const sv=assets.map((a,k)=>shares.SMART_DCA[k]*prices[k]),st=sv.reduce((a,b)=>a+b,0)+cash.SMART_DCA,sw=smartWeights({assets,weights,values:sv,total:st,priceArrays,i});maxSmartWeight=Math.max(maxSmartWeight,...sw);assets.forEach((a,k)=>{const amt=monthly*sw[k];shares.SMART_DCA[k]+=amt/prices[k];cash.SMART_DCA-=amt});}
for(const n of names){minCash[n]=Math.min(minCash[n],cash[n]);if(cash[n]<-1e-6)throw new Error(n+' negative cash');const value=cash[n]+shares[n].reduce((s,q,k)=>s+q*prices[k],0);series[n].push({date,value,flow})}}
const result={contributed,contributionCount,minCash,maxSmartWeight,dates:dates.slice(startIndex),series,metrics:{}};for(const n of names)result.metrics[n]=metrics(series[n],flows[n]);return result}
function rolling({assets,monthly=1000,macroAt=()=>50,windowSessions=252,step=21}){const aligned=alignAssets(assets),out=[];for(let start=252;start+windowSessions<=aligned.dates.length;start+=step){const end=start+windowSessions,sub=assets.map((a,k)=>({name:a.name,weight:a.weight,history:aligned.dates.slice(0,end).map(d=>({date:d,close:aligned.maps[k].get(d)}))})),r=simulate({assets:sub,monthly,macroAt,startIndex:start});out.push({start:aligned.dates[start],end:aligned.dates[end-1],tech:r.metrics.MR_TECH.twrAnnual-r.metrics.DCA.twrAnnual,macro:r.metrics.MR_MACRO.twrAnnual-r.metrics.DCA.twrAnnual,smart:r.metrics.SMART_DCA.twrAnnual-r.metrics.DCA.twrAnnual})}return out}
module.exports={avg,clamp,maxDrawdown,xirr,metrics,opportunity,drawdownAt,smartWeights,alignAssets,simulate,rolling};
